name: Release
on:
  push:
    branches: [main]
    tags:
      - "v*"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - uses: actions/setup-node@v3.8.1

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: wasm32-wasip1

      - name: Cache CPython
        id: cache-cpython-wasi
        uses: actions/cache@v3
        with:
          path: cpython/builddir/wasi
          key: cpython-wasi
          enableCrossOsArchive: true

      - name: Build
        shell: bash
        run: make -j4

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
            name: wasi-wheels
            path: build/*-wasi.tar.gz

      - name: Upload binary to Github release (tag)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/*-wasi.tar.gz
          tag: ${{ github.ref }}